### ISSUE TITLE
finalizedPoolCount gives a negative number

### ISSUE THREAD

**Issue by rbval** [balancer-labs/balancer-subgraph#61]
We use Balancer's `finalizedPoolCount` to get the total number of pools to query data from:

![image](https://user-images.githubusercontent.com/6399810/100523164-f938f300-31b6-11eb-9f0f-3a09f99d949b.png)

at block height 10118632 this number is positive however:

![image](https://user-images.githubusercontent.com/6399810/100523578-33f05a80-31ba-11eb-9b25-d01b8a7a0d01.png)

Curious if there's some bug in the graph mapper?

**Comment by bonustrack** [comment]
@rbval Good question, i know it was working previously because we were using this on our UI, i'm not sure when it stop working, but i do see much change in the code that would explain that. I'm trying some changes to fix that on our beta subgraph: https://thegraph.com/explorer/subgraph/balancer-labs/balancer-beta?version=pending it will need a bit of time to be fully sync.

**Comment by bonustrack** [comment]
With the change, the count of pool is now positive and seem to be working fine, i'm closing this issue feel free to reopen if needed.
